name: Anthro New England
favicon: null
layout_spectrum: 0.9368650142569095
typography_spectrum: 0.2734957616776228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6211339174769819
  lightness: 0.8799932894762605
  saturation: 0.22357204067520797
  rhythmicContrast: 0.5724507914856076
purpose: []
